#ifndef ENVIRONMENT_SECRETS_H
#define ENVIRONMENT_SECRETS_H

#define WIFI_SSID "A WIFI SSID HERE"
#define WIFI_PASSWORD "THE PASSWORD OF THE WIFI"
#define SLACK_WEBHOOK_URL "https://hooks.slack.com/services/T0XXXXXXX/B0XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX"
#define SIM_PIN "1234"

#endif